SEP6_frontendd/Controllers/DestinationsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChartJSCore.Models;
using SEP6_frontendd.Util;

namespace SEP6_frontendd.Controllers
{
    public class DestinationsController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.SuccessBody = ApiCalls.GetDestinationFlights();

            var flightsOrigins = ApiCalls.GetDestinationOrigins();

            List<string> dests = new List<string>();
            
            List<List<double?>> counts = new List<List<double?>>();

            List<string> origins = new List<string>();

            foreach (var flightsOrigin in flightsOrigins)
            {
                if (!origins.Contains(flightsOrigin.Origin))
                {
                    origins.Add(flightsOrigin.Origin);
                }

                List<double?> countList = new List<double?>();

                foreach (var flight in flightsOrigin.Flights)
                {
                    countList.Add(flight.count);
                }

                counts.Add(countList);

                foreach (var flight in flightsOrigin.Flights)
                {
                    if (!dests.Contains(flight.Destination))
                    {
                        dests.Add(flight.Destination);
                    }
                }

                

            }

            Chart chart1 = BarCharts.BuildColorfulBarChartWithManyDatasets(dests, counts, origins);

            ViewData["chart1"] = chart1;

            return View();
        }
    }
}

SEP6_frontendd/Controllers/PlanesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SEP6_frontendd.Controllers
{
    public class PlanesController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.table1 = ApiCalls.GetManufacturers200();
            ViewBag.table2 = ApiCalls.GetManufacturersFlights();
            ViewBag.table3 = ApiCalls.GetAirbuses();
            return View();
        }
    }
}

SEP6_frontendd/Controllers/TrackerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SEP6_frontendd.Controllers
{
    public class TrackerController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.SuccessBody = ApiCalls.GetMeanAirtime();
            ViewBag.table2 = ApiCalls.GetMeanDelay();
            return View();
        }
    }
}

SEP6_frontendd/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChartJSCore.Models;
using SEP6_frontendd.ApiModels;
using SEP6_frontendd.Util;

namespace SEP6_frontendd.Controllers
{
    public class WeatherController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.SuccessBody = ApiCalls.GetWeathersByOrigin();

            var temperatures = ApiCalls.GetTemperaturesJfk();

            var chart1 = BubbleCharts.BuildTemperatureBubbleChart(temperatures);

            var temperaturesOrigin = ApiCalls.GetTemperatureAttributes();

            var chartAtt1 = BubbleCharts.BuildTemperatureAttributesBubbleChart(temperaturesOrigin[0], Colors.GetRed(), Colors.GetRedBorder());

            var chartAtt2 = BubbleCharts.BuildTemperatureAttributesBubbleChart(temperaturesOrigin[1], Colors.GetBlue(), Colors.GetBlueBorder());

            var chartAtt3 = BubbleCharts.BuildTemperatureAttributesBubbleChart(temperaturesOrigin[2], Colors.GetGreen(), Colors.GetGreenBorder() );

            var meanTemperatures = ApiCalls.GetMeanTemperaturesJfk();

            var chart3 = BubbleCharts.BuildTemperatureBubbleChart(meanTemperatures);

            var meanTemperaturesOrigin = ApiCalls.GetMeanTemperaturesOrigin();

            var chart4 = BubbleCharts.BuildTemperatureAttributesBubbleChart1(meanTemperaturesOrigin);

            ViewData["chart1"] = chart1;

            ViewData["chart21"] = chartAtt1;

            ViewData["chart22"] = chartAtt2;

            ViewData["chart23"] = chartAtt3;

            ViewData["chart3"] = chart3;

            ViewData["chart4"] = chart4;

            return View();
        }
    }
}

SEP6_frontendd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UAA Flights</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        h1 {
            padding: 50px;
            font-family: Calibri;
            text-transform: uppercase;
        }

        table {
            margin-left: 5%;
        }

        th {
            background-color: lightgray;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">

            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UAA Flights</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Destinations" asp-action="Index">Destinations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Tracker" asp-action="Index">Tracker</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Weather" asp-action="Index">Weather</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Planes" asp-action="Index">Planes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SEP6_frontendd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>